server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://43.143.33.99:3306/zut-shop?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: roydon
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  redis:
    host: 43.143.33.99
    port: 6379
    database: 7
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss: #七牛云对象存储
  accessKey: 5QiJWZTAE8CCDpjiJyy8RlxZWtPzUP0CEWX-_O3i
  secretKey: S6tbwe-RyZ1R3KN3APYpVYtC5gcnpnCUFTkFWx51
  bucket: zut-shop-avatar